"""add user_profiles table

Revision ID: 611c32a6b0ff
Revises: 484c0d7874e1
Create Date: 2026-09-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611c32a6b0ff'
down_revision: Union[str, None] = '484c0d7874e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desired_role', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Enum('entry', 'mid', 'senior', 'lead', name='experience_level'), nullable=True),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('remote_preference', sa.Enum('remote', 'hybrid', 'onsite', 'any', name='remote_preference'), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', name='employment_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.execute('DROP TYPE IF EXISTS experience_level')
    op.execute('DROP TYPE IF EXISTS remote_preference')
    op.execute('DROP TYPE IF EXISTS employment_type')
    # ### end Alembic commands ###